# Site settings
title: cjdns
description: "cjdns: secure decentralized meshnet"
baseurl: "/cjdns-website/"
url: "http://mawalu.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

style:
#    body: "whitesmoke"
    anchor: "#46f"
    nav: "#333"
    description: "white"
    article:
        odd: "#fbfbfb"
        even: "#54626F"
