# Site settings
title: cjdns
description: "cjdns: secure decentralized meshnet"
baseurl: "/cjdns-website/"
url: "http://mawalu.github.io/"

# Build settings
markdown: redcarpet
permalink: /:categories/:title/
