# Site settings
title: cjdns
description: "cjdns: secure decentralized meshnet"
baseurl: "/cjdns-website/"
url: "http://mawalu.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

style:
#    body: "whitesmoke"
    nav: "#181818"
    article:
        even: "white"
        odd: "#222222"
