title: "cjdns"
description: "cjdns: secure decentralized meshnet"
url: "http://mawalu.github.io/"
baseurl: "/cjdns-website" # comment out if in root directory

style:
#    body: "whitesmoke"
    padding: 25%
#    anchor: "#46f"
    serif-heading: false
    nav: "#333"
    headline: "#06f"
    description: "white"
    article:
        odd: "#54626F"
        even: "#fbfbfb"
